### ISSUE TITLE
중간발표를 위한 구조도 제작

### ISSUE THREAD

**Issue by chris0765** [kookmin-sw/capstone-2023-10#10]
현재 작성해둔 구조도는 단순 역할만 나열되었을 뿐, 어떤 서비스를 이용하여 실행할 것인지 등에 대한 정보가 나타나있지 않음.

이를 해결하기 위한 새로운 구조도 작성

![image](https://user-images.githubusercontent.com/66048830/227793026-09ff2e24-17f6-44f6-b8f8-c86dd6558bb2.png)

**Comment by chris0765** [comment]
![ArchitectureBlueprint](https://user-images.githubusercontent.com/66048830/227796770-7eaae0b5-28b9-4adc-a550-9e19b22acd82.png)

1차 작성.

우선 작성해뒀으나 계속해서 개선해나가야할듯합니다.
개선하는게 좋을만한 포인트가 있으면 코멘트 남겨주시면 반영하겠습니다.

우선 저는 글자 배치하는 위치가 애매한게 맘에 안드는 부분이기는 한데, 더 옮길만한 공간이 없기도 하고, 글자를 아예 없애자니 이해하기 힘들 것 같아 저렇게 배치해두었습니다.

모델의 형식 역시 기입해두는 것이 좋을 것 같은데, RNN이냐 LSTM이냐 Transformer냐 아직 정해진 부분은 없는 것 같아 그냥 Model로 작성해두었습니다.

**Comment by chris0765** [comment]
![ArchitectureBlueprint](https://user-images.githubusercontent.com/66048830/227797247-583417a3-2e6d-4bd5-b768-4c9f6f510d55.png)


1차 작성.

우선 작성해뒀으나 계속해서 개선해나가야할듯합니다.
개선하는게 좋을만한 포인트가 있으면 코멘트 남겨주시면 반영하겠습니다.

우선 저는 글자 배치하는 위치가 애매한게 맘에 안드는 부분이기는 한데, 더 옮길만한 공간이 없기도 하고, 글자를 아예 없애자니 이해하기 힘들 것 같아 저렇게 배치해두었습니다.

모델의 형식 역시 기입해두는 것이 좋을 것 같은데, RNN이냐 LSTM이냐 Transformer냐 아직 정해진 부분은 없는 것 같아 그냥 Model로 작성해두었습니다.

**Comment by chris0765** [comment]
![ArchitectureBlueprint](https://user-images.githubusercontent.com/66048830/227797302-cb560113-a886-4958-b2e6-0efbf650780b.png)

1차로 구조도 작성 완료했습니다.

급한대로 작성은 해 두었는데 피드백 할 부분 있으면 코멘트 남겨주세요.

일단 개인적으로는 텍스트 위치가 마음에 들지는 않는데, 아래 그림처럼 ppt 화면 거의 전체를 이미 다 쓰고 있기도 하고, 텍스트를 없애자니 이해가 어려울 것 같아서 저렇게 어중간하게 넣어두었습니다.

![image](https://user-images.githubusercontent.com/66048830/227797345-834fd611-a6de-4a55-8249-c81e57cea6db.png)

그리고 모델의 형식 역시 RNN인지 DNN인지 LSTM인지 Transformer인지 어떤건지 작성해두고 싶은데, 아직 명확하게 정해진 바는 없는 것 같아 그냥 Model로 작성해두었습니다.

**Comment by chris0765** [comment]
![ArchitectureBlueprint](https://user-images.githubusercontent.com/66048830/228311166-841ccf26-569f-47bb-8ed5-8bde152be3f7.png)

변경점
* 체크포인트 파일을 저장하는 시스템을 구조도에 추가했습니다.
* 글자 뒷부분에 하얀 박스를 추가하여 구조도의 이미지와 겹치지 않도록 했습니다.
* ELB에 외부 ip가 사용 불가능하다는 답변을 받아, ELB 시스템을 Route 53 시스템으로 변경했습니다.

**Comment by chris0765** [comment]
![ArchitectureBlueprint_whitebackground](https://user-images.githubusercontent.com/66048830/229359450-81b377bb-cf71-41ef-b7d1-8c678b3713bf.png)

여러 피드백 반영하여 최종 구조도 완성했습니다.

설명을 위해 1, 2, 3 등 넘버링을 한 그림은 아래와 같습니다.

![ArchitectureBlueprint_whitebackground_withnumber](https://user-images.githubusercontent.com/66048830/229359438-252a0365-781b-4cb2-b4e6-4534ccdb73eb.png)

**Comment by chris0765** [comment]
Readme, Github Page 등에 업데이트 해주시면 될 것 같습니다.

**Comment by kh3654po** [comment]
![ArchitectureBlueprint_New](https://github.com/kookmin-sw/capstone-2023-10/assets/54831356/7b42648d-8aee-49dc-a161-61b0e0361809)
