### ISSUE TITLE
중간발표를 위한 자료 제작

### ISSUE THREAD

**Issue by chris0765** [kookmin-sw/capstone-2023-10#11]
- [x] 보고서
- [x] 발표 ppt
- [x] 대본 작성

자료 제작 과정과 대본 내용에 대한 수정 과정을 작성해둘 이슈

**Comment by chris0765** [comment]
[중간발표보고서.pdf](https://github.com/kookmin-sw/capstone-2023-10/files/11074326/default.pdf)

우선 중간발표 보고서도 작성해봤습니다.
생각보다 개요 설명 말고는 적을 내용이 많지가 않네요.
대충 그림으로 그려서라도 주피터 노트북 결과물을 끼워넣어도 될 것 같기도 하고요.

피드백 부탁드립니다.

**Comment by chris0765** [comment]
피드백 내용대로 앞부분 설명을 조금 더 자세하게 작성했으며, 예상 결과물 이미지 설명을 추가했습니다.

[캡스톤팀10중간발표보고서.pdf](https://github.com/kookmin-sw/capstone-2023-10/files/11092244/10.pdf)

**Comment by chris0765** [comment]
발표자료 제작 및 개선

* 보고서
[캡스톤팀10중간발표보고서.pdf](https://github.com/kookmin-sw/capstone-2023-10/files/11132815/10.pdf)

피드백 반영하여 볼드체, 밑줄 등으로 강조해야할 부분 표시하였으며, 구조도 설명도 그룹을 묶어 숫자로 나타내는 설명 추가하는 등을 통해 개선했습니다.

* 피피티
[캡스톤중간발표.pdf](https://github.com/kookmin-sw/capstone-2023-10/files/11132842/default.pdf)
[캡스톤중간발표.pptx](https://github.com/kookmin-sw/capstone-2023-10/files/11132843/default.pptx)

이창우 교수님께서 피피티의 색감이 조금 쨍하다라고 말씀해주신 바가 있어, 색깔을 변경했습니다.
전/후 비교해서 어떤게 더 나을지 판단 부탁드립니다.

[캡스톤중간발표_OLD.pdf](https://github.com/kookmin-sw/capstone-2023-10/files/11132847/_OLD.pdf)
피피티 개선 이전 자료로, 색감 판단에만 사용해주시면 될듯합니다.

* 대본
[캡스톤중간발표대본.docx](https://github.com/kookmin-sw/capstone-2023-10/files/11132818/default.docx)

현재 발표 분량은 5분 30초정도 진행됩니다.
1분 30초정도 여유가 있으므로 어느정도 분량을 추가할지,
아니면 질의응답이 많이 나올 것 같으니 1분 30초의 여유 분량을 질의응답에 추가할지 의견 제시 부탁드립니다.

**Comment by zisoooo** [comment]
ppt는 바뀐 색이 더 보기에 편안한 것 같아서 바꾼걸로 하면 될 것 같습니다.
발표는 분량을 추가하는 게 좋을 것 같은데, 질문이 들어올 만한 내용을 발표 분량으로 약간 추가하는 건 어떨까요?
