### ISSUE TITLE
Migration 시스템 구현

### ISSUE THREAD

**Issue by chris0765** [kookmin-sw/capstone-2023-10#17]
인스턴스를 생성하고, 주어진 서브넷 내에 스팟 인스턴스를 요청하는 기능 개발

**Comment by chris0765** [comment]
#15 이슈로 기본적인 스켈레톤 코드 작성 완료.

대부분의 부분이 자동적으로 작동하게 하기 위해, AWS 부분을 작성하며 AMI ID를 자동으로 알아내서 사용하도록 설정하고자 하였지만, Red Hat으로 한정지어도 너무 많은 AMI가 존재해 단 2개의 AMI를 추려내기 어렵다는 한계에 도달, AMI도 boto3 profile과 같이 사용자가 직접 추가하는 변수로 설정해두었습니다.

**Comment by chris0765** [comment]
스팟 인스턴스를 요청하는 기능 부분을 구현해야하는데, 
Subnet 정보로 어떤 것들이 필요한지 각 벤더별로 알려주시면 도움이 될 것 같습니다.
예) Subnet ID 어디어디에 생성, Security Group은 어떤어떤걸 사용 등
@kh3654po

**Comment by kh3654po** [comment]
https://purple-society-3a6.notion.site/VPN-7a92811438e6440c97db47081ec221c5 여기에 정리해놓았습니다. 한번 확인해보시고 궁금한거 있으시면 물어보세요

**Comment by chris0765** [comment]
마이그레이션 모듈 init() 정상 작동까지 테스트 완료.
terraform 수정을 통해 ALB와 target group, security group의 포트가 :80이 아닌 :8800이 될 수 있도록 수정해야 ALB 링크를 통해 정상 작동 되는지를 테스트 할 수 있을듯 함.

**Comment by chris0765** [comment]
#28 을 통해 완료
