### ISSUE TITLE
메인워커 시스템 구현

### ISSUE THREAD

**Issue by kh3654po** [kookmin-sw/capstone-2023-10#7]
### 구현하려는 시스템
  * 사용자의 입력을 받아 모델 추천 시스템로 전달하고 인스턴스 리스트를 받는다.
  * 해당 인스턴스를 실행하고 주피터노트북을 실행한다.
  * 클라우드 벤더로부터 스팟인스턴스 종료 경고가 오면 새로운 인스턴스 리스트를 받아 생성하고 podman checkpoint를 사용해 사용자의 작업이 끊기지 않도록 마이그레이션 한다.
  * 사용자가 사용중간에 원하는 스펙을 변경하면 해당 스펙의 인스턴스로 전환해준다.

**Comment by kh3654po** [comment]
[] dns 서비스 구성
[] 인스턴스 마이그레이션

**Comment by chris0765** [comment]
본 이슈는 메인 인스턴스 구조의 변경으로 close
